spring.application.name=Sarismart Backend API

# Spring Boot Configuration
spring.datasource.url=postgresql://postgres:${SUPABASE_PASSWORD}@mpvwyygeoesopxralxxl.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# HikariCP Configuration
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=120000

server.tomcat.accesslog.enabled=true
spring.jpa.properties.hibernate.ddl-auto=update
spring.jpa.show_sql=true